// GhostRig.cginc — GENERATED by GhostMeshBuilder. Default generic humanoid until you bake.
// Rest bone positions in rig space, hips at origin, metres. Order matches POSE_FORMAT.md.
#ifndef GHOST_RIG_INCLUDED
#define GHOST_RIG_INCLUDED

#define GHOST_BONES 19
// Eye height of the rig in metres; captured height / this = ghost scale
#define GHOST_RIG_EYE_HEIGHT 1.60

static const float3 GHOST_REST[GHOST_BONES] = {
    float3( 0.00,  0.00, 0), // 0 Hips
    float3( 0.00,  0.10, 0), // 1 Spine
    float3( 0.00,  0.25, 0), // 2 Chest
    float3( 0.00,  0.45, 0), // 3 Neck
    float3( 0.00,  0.55, 0), // 4 Head
    float3(-0.05,  0.42, 0), // 5 LShoulder
    float3(-0.17,  0.42, 0), // 6 LUpperArm
    float3(-0.43,  0.42, 0), // 7 LLowerArm
    float3(-0.68,  0.42, 0), // 8 LHand
    float3( 0.05,  0.42, 0), // 9 RShoulder
    float3( 0.17,  0.42, 0), // 10 RUpperArm
    float3( 0.43,  0.42, 0), // 11 RLowerArm
    float3( 0.68,  0.42, 0), // 12 RHand
    float3(-0.09, -0.05, 0), // 13 LUpperLeg
    float3(-0.09, -0.50, 0), // 14 LLowerLeg
    float3(-0.09, -0.92, 0), // 15 LFoot
    float3( 0.09, -0.05, 0), // 16 RUpperLeg
    float3( 0.09, -0.50, 0), // 17 RLowerLeg
    float3( 0.09, -0.92, 0)  // 18 RFoot
};

static const int GHOST_PARENT[GHOST_BONES] = {
    -1, 0, 1, 2, 3,  2, 5, 6, 7,  2, 9, 10, 11,  0, 13, 14,  0, 16, 17
};

// Segment used to orient vertices bound to bone i.
// >=0 : direction from bone i toward this child.  -1 : direction from parent toward bone i (leaf).
static const int GHOST_SEG_CHILD[GHOST_BONES] = {
    1, 2, 3, 4, -1,  6, 7, 8, -1,  10, 11, 12, -1,  14, 15, -1,  17, 18, -1
};

#endif
